version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ../../models:/app/models
    networks:
      - art-network

  app:
    build: ./app
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - art-network

networks:
  art-network:
    driver: bridge